/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModeratorRouteRouteImport } from './routes/moderator/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeratorIndexRouteImport } from './routes/moderator/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthCallbackRouteImport } from './routes/_auth/callback'
import { Route as AdminModeratorsRouteRouteImport } from './routes/admin/moderators/route'
import { Route as ModeratorLoginIndexRouteImport } from './routes/moderator/login/index'
import { Route as AdminModeratorsIndexRouteImport } from './routes/admin/moderators/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AuthSignUpSplatRouteImport } from './routes/_auth/sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/_auth/sign-in.$'

const ModeratorRouteRoute = ModeratorRouteRouteImport.update({
  id: '/moderator',
  path: '/moderator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorIndexRoute = ModeratorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeratorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminModeratorsRouteRoute = AdminModeratorsRouteRouteImport.update({
  id: '/moderators',
  path: '/moderators',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ModeratorLoginIndexRoute = ModeratorLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => ModeratorRouteRoute,
} as any)
const AdminModeratorsIndexRoute = AdminModeratorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminModeratorsRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/moderator': typeof ModeratorRouteRouteWithChildren
  '/admin/moderators': typeof AdminModeratorsRouteRouteWithChildren
  '/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/moderator/': typeof ModeratorIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/moderators/': typeof AdminModeratorsIndexRoute
  '/moderator/login/': typeof ModeratorLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof AuthCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/moderator': typeof ModeratorIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/moderators': typeof AdminModeratorsIndexRoute
  '/moderator/login': typeof ModeratorLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/moderator': typeof ModeratorRouteRouteWithChildren
  '/admin/moderators': typeof AdminModeratorsRouteRouteWithChildren
  '/_auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/moderator/': typeof ModeratorIndexRoute
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/moderators/': typeof AdminModeratorsIndexRoute
  '/moderator/login/': typeof ModeratorLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/moderator'
    | '/admin/moderators'
    | '/callback'
    | '/admin/'
    | '/moderator/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/dashboard/'
    | '/admin/moderators/'
    | '/moderator/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/admin'
    | '/moderator'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/dashboard'
    | '/admin/moderators'
    | '/moderator/login'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/moderator'
    | '/admin/moderators'
    | '/_auth/callback'
    | '/admin/'
    | '/moderator/'
    | '/_auth/sign-in/$'
    | '/_auth/sign-up/$'
    | '/admin/dashboard/'
    | '/admin/moderators/'
    | '/moderator/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ModeratorRouteRoute: typeof ModeratorRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/moderator': {
      id: '/moderator'
      path: '/moderator'
      fullPath: '/moderator'
      preLoaderRoute: typeof ModeratorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/': {
      id: '/moderator/'
      path: '/'
      fullPath: '/moderator/'
      preLoaderRoute: typeof ModeratorIndexRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/moderators': {
      id: '/admin/moderators'
      path: '/moderators'
      fullPath: '/admin/moderators'
      preLoaderRoute: typeof AdminModeratorsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/moderator/login/': {
      id: '/moderator/login/'
      path: '/login'
      fullPath: '/moderator/login/'
      preLoaderRoute: typeof ModeratorLoginIndexRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/admin/moderators/': {
      id: '/admin/moderators/'
      path: '/'
      fullPath: '/admin/moderators/'
      preLoaderRoute: typeof AdminModeratorsIndexRouteImport
      parentRoute: typeof AdminModeratorsRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AdminModeratorsRouteRouteChildren {
  AdminModeratorsIndexRoute: typeof AdminModeratorsIndexRoute
}

const AdminModeratorsRouteRouteChildren: AdminModeratorsRouteRouteChildren = {
  AdminModeratorsIndexRoute: AdminModeratorsIndexRoute,
}

const AdminModeratorsRouteRouteWithChildren =
  AdminModeratorsRouteRoute._addFileChildren(AdminModeratorsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminModeratorsRouteRoute: typeof AdminModeratorsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminModeratorsRouteRoute: AdminModeratorsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ModeratorRouteRouteChildren {
  ModeratorIndexRoute: typeof ModeratorIndexRoute
  ModeratorLoginIndexRoute: typeof ModeratorLoginIndexRoute
}

const ModeratorRouteRouteChildren: ModeratorRouteRouteChildren = {
  ModeratorIndexRoute: ModeratorIndexRoute,
  ModeratorLoginIndexRoute: ModeratorLoginIndexRoute,
}

const ModeratorRouteRouteWithChildren = ModeratorRouteRoute._addFileChildren(
  ModeratorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ModeratorRouteRoute: ModeratorRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
